# ============================== Server ==============================

[server]
host = "127.0.0.1"
port = 8080

[main_page]
title = "LunaFinder"
description = "Made with ğŸ’• by imnya.ng"
markdown_file = "./page.md"  # ë©”ì¸ í˜ì´ì§€ì— í‘œì‹œí•  ë§ˆí¬ë‹¤ìš´ íŒŒì¼

# ============================== Users ==============================

[user.imnyang]
password = "a"
group = ["admin"] # if group is admin, user can manage other users
hash_algorithm = "plain"  # ì§€ì›ë˜ëŠ” í•´ì‹œ ì•Œê³ ë¦¬ì¦˜: argon2, bcrypt, sha256, plain
# password í•„ë“œê°€ ë¹„ì–´ ìˆìœ¼ë©´ ì¸ì¦ì´ ë¹„í™œì„±í™”ë©ë‹ˆë‹¤.

[user.neko]
password = ""
group = ["cat"]
hash_algorithm = "argon2"  # ì§€ì›ë˜ëŠ” í•´ì‹œ ì•Œê³ ë¦¬ì¦˜: argon2, bcrypt, sha256, plain
# password í•„ë“œê°€ ë¹„ì–´ ìˆìœ¼ë©´ ì¸ì¦ì´ ë¹„í™œì„±í™”ë©ë‹ˆë‹¤.

# ============================== Mounts ==============================

[mounts.home]
path = "./files/home"
description = "Home directory"
public = true  # ì¸ì¦ ì—†ì´ ì ‘ê·¼ ê°€ëŠ¥
group.admin = "admin"

[mounts.documents]
path = "./files/documents"
description = "Documents storage"
group.cat = ["viewer", "uploader"] # cat ê·¸ë£¹ì— ë·°ì–´/ì—…ë¡œë” ê¶Œí•œ ë¶€ì—¬
group.admin = "admin"

[mounts.fur]
path = "./files/fur"
description = "fur files"
user.neko = "read" # neko ì‚¬ìš©ìì—ê²Œ ì½ê¸° ì „ìš© ê¶Œí•œ ë¶€ì—¬
group.admin = "admin"

# ============================== Permissions ==============================

[permissions.viewer]
read = true

[permissions.uploader]
upload = true
create_file = true
create_folder = true

[permissions.editor]
upload = true
rename = true
delete = true
modify = true
create_file = true
create_folder = true

[permissions.admin]
read = true # ì½ê¸° ê¶Œí•œ
create_folder = true # í´ë” ìƒì„± ê¶Œí•œ
create_file = true # íŒŒì¼ ìƒì„± ê¶Œí•œ
upload = true # ì—…ë¡œë“œ ê¶Œí•œ
rename = true # ì´ë¦„ ë³€ê²½ ê¶Œí•œ
delete = true # ì‚­ì œ ê¶Œí•œ
modify = true # ìˆ˜ì • ê¶Œí•œ
write = true # í¬ê´„ì ì¸ ì“°ê¸° ê¶Œí•œ

